begin
execute immediate 'drop table DCT_REGLAMENTTYPES CASCADE CONSTRAINTS ';
exception when others
  then null;
end;
/

CREATE TABLE DCT_REGLAMENTTYPES
(
  REGLAMENTTYPE_CODE  VARCHAR2(25 BYTE)         NOT NULL,
  REGLAMENTTYPE_NAME  VARCHAR2(255 BYTE)        NOT NULL,
  REGLAMENTTYPE_DESC  VARCHAR2(512 BYTE),
  CHANGE_DATE         DATE                      DEFAULT SYSDATE               NOT NULL,
  PATCH_CODE          VARCHAR2(128 BYTE)        NOT NULL
)
TABLESPACE EDSC_META
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

CREATE UNIQUE INDEX DCT_REGLAMENTTYPES_PK ON DCT_REGLAMENTTYPES
(REGLAMENTTYPE_CODE)
TABLESPACE EDSC_META;

ALTER TABLE DCT_REGLAMENTTYPES ADD (
  CONSTRAINT DCT_REGLAMENTTYPES_PK
  PRIMARY KEY
  (REGLAMENTTYPE_CODE)
  USING INDEX DCT_REGLAMENTTYPES_PK
  ENABLE VALIDATE);

COMMENT ON TABLE DCT_REGLAMENTTYPES IS 'Типы регламентных потоков';

COMMENT ON COLUMN DCT_REGLAMENTTYPES.REGLAMENTTYPE_CODE IS 'Код типа регламентного потока';

COMMENT ON COLUMN DCT_REGLAMENTTYPES.REGLAMENTTYPE_NAME IS 'Наименование типа регламентного потока';

COMMENT ON COLUMN DCT_REGLAMENTTYPES.REGLAMENTTYPE_DESC IS 'Определение типа регламентного потока';

COMMENT ON COLUMN DCT_REGLAMENTTYPES.CHANGE_DATE IS 'Дата последнего изменения информации о событии.';

COMMENT ON COLUMN DCT_REGLAMENTTYPES.PATCH_CODE IS 'Номер последнего патча, в котором внесены изменения.';