begin
execute immediate 'drop table DCT_PARAMVALUETYPES CASCADE CONSTRAINTS ';
exception when others
  then null;
end;
/

CREATE TABLE DCT_PARAMVALUETYPES
(
  PARAMVALUETYPE_CODE  VARCHAR2(25 BYTE)        NOT NULL,
  PARAMVALUETYPE_NAME  VARCHAR2(255 BYTE)       NOT NULL,
  PARAMVALUETYPE_DESC  VARCHAR2(512 BYTE),
  CHANGE_DATE          DATE                     DEFAULT SYSDATE               NOT NULL,
  PATCH_CODE           VARCHAR2(128 BYTE)       NOT NULL
)
TABLESPACE EDSC_META
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

CREATE UNIQUE INDEX DCT_PARAMVALUETYPES_PK ON DCT_PARAMVALUETYPES
(PARAMVALUETYPE_CODE)
TABLESPACE EDSC_META;

ALTER TABLE DCT_PARAMVALUETYPES ADD (
  CONSTRAINT DCT_PARAMVALUETYPES_PK
  PRIMARY KEY
  (PARAMVALUETYPE_CODE)
  USING INDEX DCT_PARAMVALUETYPES_PK
  ENABLE VALIDATE);

COMMENT ON TABLE DCT_PARAMVALUETYPES IS 'Типы значений параметров';

COMMENT ON COLUMN DCT_PARAMVALUETYPES.PARAMVALUETYPE_CODE IS 'Код типа значения параметра';

COMMENT ON COLUMN DCT_PARAMVALUETYPES.PARAMVALUETYPE_NAME IS 'Наименование типа значения параметра';

COMMENT ON COLUMN DCT_PARAMVALUETYPES.PARAMVALUETYPE_DESC IS 'Описание типа значения параметра';

COMMENT ON COLUMN DCT_PARAMVALUETYPES.CHANGE_DATE IS 'Дата последнего изменения информации о событии.';

COMMENT ON COLUMN DCT_PARAMVALUETYPES.PATCH_CODE IS 'Номер последнего патча, в котором внесены изменения.';