begin
execute immediate 'drop table DCT_LOADINGMODES CASCADE CONSTRAINTS ';
exception when others
  then null;
end;
/

CREATE TABLE DCT_LOADINGMODES
(
  LOADINGMODE_CODE  VARCHAR2(25 BYTE)           NOT NULL,
  LOADINGMODE_NAME  VARCHAR2(255 BYTE)          NOT NULL,
  LOADINGMODE_DESC  VARCHAR2(512 BYTE),
  CHANGE_DATE       DATE                        DEFAULT SYSDATE               NOT NULL,
  PATCH_CODE        VARCHAR2(128 BYTE)          NOT NULL
)
TABLESPACE EDSC_META
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

CREATE UNIQUE INDEX DCT_LOADINGMODES_PK ON DCT_LOADINGMODES
(LOADINGMODE_CODE)
TABLESPACE EDSC_META;

ALTER TABLE DCT_LOADINGMODES ADD (
  CONSTRAINT DCT_LOADINGMODES_PK
  PRIMARY KEY
  (LOADINGMODE_CODE)
  USING INDEX DCT_LOADINGMODES_PK
  ENABLE VALIDATE);
COMMENT ON TABLE DCT_LOADINGMODES IS 'Режимы загрузки данных';

COMMENT ON COLUMN DCT_LOADINGMODES.LOADINGMODE_CODE IS 'Код типа функционального назначения';

COMMENT ON COLUMN DCT_LOADINGMODES.LOADINGMODE_NAME IS 'Наименование типа функционального назначения';

COMMENT ON COLUMN DCT_LOADINGMODES.LOADINGMODE_DESC IS 'Описание типа функционального назначения';

COMMENT ON COLUMN DCT_LOADINGMODES.CHANGE_DATE IS 'Дата последнего изменения информации о событии.';

COMMENT ON COLUMN DCT_LOADINGMODES.PATCH_CODE IS 'Номер последнего патча, в котором внесены изменения.';