begin
execute immediate 'drop table DCT_IPCOBJTYPES CASCADE CONSTRAINTS ';
exception when others
  then null;
end;
/

CREATE TABLE DCT_IPCOBJTYPES
(
  IPCOBJTYPE_CODE  VARCHAR2(25 BYTE)            NOT NULL,
  IPCOBJTYPE_NAME  VARCHAR2(255 BYTE)           NOT NULL,
  IPCOBJTYPE_DESC  VARCHAR2(512 BYTE),
  CHANGE_DATE      DATE                         DEFAULT SYSDATE               NOT NULL,
  PATCH_CODE       VARCHAR2(128 BYTE)           NOT NULL
)
TABLESPACE EDSC_META
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

CREATE UNIQUE INDEX DCT_IPCOBJTYPES_PK ON DCT_IPCOBJTYPES
(IPCOBJTYPE_CODE)
TABLESPACE EDSC_META;

ALTER TABLE DCT_IPCOBJTYPES ADD (
  CONSTRAINT DCT_IPCOBJTYPES_PK
  PRIMARY KEY
  (IPCOBJTYPE_CODE)
  USING INDEX DCT_IPCOBJTYPES_PK
  ENABLE VALIDATE);
COMMENT ON TABLE DCT_IPCOBJTYPES IS 'Типы объектов IPC';

COMMENT ON COLUMN DCT_IPCOBJTYPES.IPCOBJTYPE_CODE IS 'Код типа объекта IPC';

COMMENT ON COLUMN DCT_IPCOBJTYPES.IPCOBJTYPE_NAME IS 'Наименование типа объекта IPC';

COMMENT ON COLUMN DCT_IPCOBJTYPES.IPCOBJTYPE_DESC IS 'Описание типа объекта IPC';

COMMENT ON COLUMN DCT_IPCOBJTYPES.CHANGE_DATE IS 'Дата последнего изменения информации о событии.';

COMMENT ON COLUMN DCT_IPCOBJTYPES.PATCH_CODE IS 'Номер последнего патча, в котором внесены изменения.';