begin
execute immediate 'drop table LOG_PARAMPREVVALUE CASCADE CONSTRAINTS ';
exception when others
  then null;
end;
/

CREATE TABLE LOG_PARAMPREVVALUE
(
  FOLDER_NAME          VARCHAR2(128 BYTE)       NOT NULL,
  WORKFLOW_NAME        VARCHAR2(128 BYTE)       NOT NULL,
  IPCOBJTYPE_CODE      VARCHAR2(25 BYTE)        NOT NULL,
  IPCOBJECT_NAME       VARCHAR2(128 BYTE)       NOT NULL,
  PARAM_NAME           VARCHAR2(128 BYTE)       NOT NULL,
  LOADINGMODE_CODE     VARCHAR2(25 BYTE)        NOT NULL,
  REGLAMENTTYPE_CODE   VARCHAR2(25 BYTE)        NOT NULL,
  PARAMVALUETYPE_CODE  VARCHAR2(25 BYTE)        NOT NULL,
  PARAM_VALUE          VARCHAR2(4000 BYTE)      NOT NULL,
  JOB_ID               NUMBER(38),
  LOADING_ID           NUMBER(38),
    	CONSTRAINT LOG_PRMPRV_LOADING_FK
	  FOREIGN KEY (LOADING_ID)
			REFERENCES LOG_LOADING,
	CONSTRAINT LOG_PRMPRV_JOB_FK
	  FOREIGN KEY (JOB_ID)
			REFERENCES LOG_JOB,
	CONSTRAINT LOG_PRMPRV_PARAMVAL_FK
    FOREIGN KEY (PARAMVALUETYPE_CODE)
			REFERENCES DCT_PARAMVALUETYPES,
	CONSTRAINT LOG_PRMPRV_REGLAMTYPE_FK
		FOREIGN KEY (REGLAMENTTYPE_CODE)
		 REFERENCES DCT_REGLAMENTTYPES,
	CONSTRAINT LOG_PRMPRV_LOADINGMODE_FK
		FOREIGN KEY (LOADINGMODE_CODE)
			REFERENCES DCT_LOADINGMODES,
	CONSTRAINT LOG_PRMPRV_PARAMETER_FK
		FOREIGN KEY (PARAM_NAME)
      REFERENCES MD_PARAMETERS,
	CONSTRAINT LOG_PRMPRV_IPCOBJTYPE_FK
		FOREIGN KEY (IPCOBJTYPE_CODE)
			references DCT_IPCOBJTYPES
)
TABLESPACE EDSC_META
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON TABLE LOG_PARAMPREVVALUE IS 'Журнал значений параметров исполняемых потоков';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.FOLDER_NAME IS 'Физическое имя папки IPC';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.WORKFLOW_NAME IS 'Физическое имя потока IPC.';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.IPCOBJTYPE_CODE IS 'Определяет тип объекта IPC, для которого в файле параметров.';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.IPCOBJECT_NAME IS 'Имя объекта (сессия, ворклет) для которого будет создаваться секция в файле параметров.';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.PARAM_NAME IS 'Имя параметра';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.LOADINGMODE_CODE IS 'Указыается режим для какого режима выполняется определ';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.REGLAMENTTYPE_CODE IS 'Указывается, для какого типа регламента  определяется значение параметра.';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.PARAMVALUETYPE_CODE IS 'Определяет, в каком режиме типа значения параметра получено значение';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.PARAM_VALUE IS 'Значение';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.JOB_ID IS 'Идентификатор исполнения функционального потока, для которого установлено значение параметра. Логическая ссылка на таблицу LOG_JOB';

COMMENT ON COLUMN LOG_PARAMPREVVALUE.LOADING_ID IS 'Идентификатор исполнения Управляющего потока. Логическая ссылка на таблицу LOG_LOADING.';