delete from DCT_DATATYPES;

INSERT INTO DCT_DATATYPES (DATATYPE_CODE, DATATYPE_NAME, DATATYPE_FORMAT, CHANGE_DATE, PATCH_CODE)
VALUES ('VARCHAR2', 'Символьный тип', null, SYSDATE, 'INITIAL');
INSERT INTO DCT_DATATYPES (DATATYPE_CODE, DATATYPE_NAME, DATATYPE_FORMAT, CHANGE_DATE, PATCH_CODE)
VALUES ('NUMBER', 'Численный тип данных', null, SYSDATE, 'INITIAL');
INSERT INTO DCT_DATATYPES (DATATYPE_CODE, DATATYPE_NAME, DATATYPE_FORMAT, CHANGE_DATE, PATCH_CODE) 
VALUES ('DATE', 'Дата/время', null, SYSDATE, 'INITIAL');

commit;