delete from DCT_REGLAMENTTYPES;

INSERT INTO DCT_REGLAMENTTYPES (REGLAMENTTYPE_CODE, REGLAMENTTYPE_NAME, REGLAMENTTYPE_DESC, PATCH_CODE)
  VALUES ( 'REGULAR_D', '≈жедневный регламент', NULL , 'INITIAL');
  
INSERT INTO DCT_REGLAMENTTYPES (REGLAMENTTYPE_CODE, REGLAMENTTYPE_NAME, REGLAMENTTYPE_DESC, PATCH_CODE)
  VALUES ( 'REGULAR_W', '≈женедельный регламент', NULL , 'INITIAL');
  
INSERT INTO DCT_REGLAMENTTYPES (REGLAMENTTYPE_CODE, REGLAMENTTYPE_NAME, REGLAMENTTYPE_DESC, PATCH_CODE)
  VALUES ( 'REGULAR_M', '≈жемес€чный регламент', NULL, 'INITIAL' );
  
INSERT INTO DCT_REGLAMENTTYPES (REGLAMENTTYPE_CODE, REGLAMENTTYPE_NAME, REGLAMENTTYPE_DESC, PATCH_CODE)
  VALUES ( 'RELOAD', '–егламент перезагрузки данных', NULL, 'INITIAL' );
  
INSERT INTO DCT_REGLAMENTTYPES (REGLAMENTTYPE_CODE, REGLAMENTTYPE_NAME, REGLAMENTTYPE_DESC, PATCH_CODE)
  VALUES ( 'CYCLE', '–егламент циклической перезагрузки данных', NULL, 'INITIAL' );
  
COMMIT;