delete from DCT_IPCOBJTYPES;

Insert into DCT_IPCOBJTYPES (IPCOBJTYPE_CODE, IPCOBJTYPE_NAME, IPCOBJTYPE_DESC, PATCH_CODE)
   Values
   ('WKF', 'Workflow', 'Поток', 'INITIAL');
Insert into DCT_IPCOBJTYPES
  (IPCOBJTYPE_CODE, IPCOBJTYPE_NAME, IPCOBJTYPE_DESC, PATCH_CODE)
 Values
   ('SES', 'Session', 'Сессия', 'INITIAL');
 Insert into DCT_IPCOBJTYPES
  (IPCOBJTYPE_CODE, IPCOBJTYPE_NAME, IPCOBJTYPE_DESC, PATCH_CODE)
 Values
   ('GLB', 'GLOBAL', NULL, 'INITIAL');
 Insert into DCT_IPCOBJTYPES
   (IPCOBJTYPE_CODE, IPCOBJTYPE_NAME, IPCOBJTYPE_DESC, PATCH_CODE)
 Values
   ('SRV', 'SERVICE', NULL, 'INITIAL');
  Insert into DCT_IPCOBJTYPES
   (IPCOBJTYPE_CODE, IPCOBJTYPE_NAME, IPCOBJTYPE_DESC, PATCH_CODE)
 Values
   ('WKLT', 'WORKLET', NULL, 'INITIAL');
COMMIT;
