delete from DCT_PURPOSETYPES;

INSERT INTO DCT_PURPOSETYPES(PURPOSETYPE_CODE, PURPOSETYPE_NAME, PURPOSETYPE_DESC, PATCH_CODE)
VALUES ('CTL', '”правл€ющий поток', NULL, 'INITIAL');

INSERT INTO DCT_PURPOSETYPES(PURPOSETYPE_CODE, PURPOSETYPE_NAME, PURPOSETYPE_DESC, PATCH_CODE)
VALUES ('REG', '–егламентный поток', NULL, 'INITIAL');

INSERT INTO DCT_PURPOSETYPES(PURPOSETYPE_CODE, PURPOSETYPE_NAME, PURPOSETYPE_DESC, PATCH_CODE)
VALUES ('ETL', '‘ункциональный поток', NULL, 'INITIAL');

commit;