UPDATE MD_IPCOBJPARAMS
SET    PARAM_VALUE = 'TO_CHAR(TRUNC(SYSDATE)-3, ''yyyymmdd'')'
WHERE  FOLDER_NAME = 'EDGOOGLE_STG' AND WORKFLOW_NAME in ('WF_REQ2ETL_GA2HDFS_ALFABANK_2018_ga_sessions','WF_REQ2ETL_GA2HDFS_ALFABANK_2018_CostData') AND PARAM_NAME = '$$P_START_DATE';
COMMIT;
